name: run unit tests of feature branches

on: 
  push:
    branches: 
      'features/*'

jobs:
  run-unit-test
    ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: run-unit-test
        run: mvn test
